### ISSUE TITLE
request the report

### ISSUE THREAD

**Issue by KippaZou** [thynnmas/polar-flow-gpx-export#1]
Hello, I can't dind the Report on acp142 (P_MUL) Java implementation. Could please send me the report if you see the request?

**Comment by thynnmas** [comment]
I'm afraid I no longer have that report on my machine or any backup I can currently get to. It's a 5 year old student project done for a third party (and I'm not even sure anymore if they were OK with us sharing the report. I think so, given that the code was open sourced, but I can't be certain). Perhaps others on the project still have it, although I would not expect it.

**Comment by KippaZou** [comment]
Thank you! I've already received the report. 

    On Wednesday, January 24, 2018 2:03 AM, Tommy Schmid <notifications@github.com> wrote:
 

 I'm afraid I no longer have that report on my machine or any backup I can currently get to. It's a 5 year old student project done for a third party (and I'm not even sure anymore if they were OK with us sharing the report. I think so, given that the code was open sourced, but I can't be certain). Perhaps others on the project still have it, although I would not expect it.—
